### ISSUE TITLE
Application problems

### ISSUE THREAD

**Issue by Photographix** [ReactiveMatter/dokuwiki-obsidian#1]
Hello, 

I have changed the paths in the script as indicated.
```
# Define the source and destination folders
source_folder = 'Volumes/cloud/dokuwiki/_data/dokuwiki' #<-- Dokuwiki Webroot
destination_folder = 'Volumes/Data/Syncthing/Obsidian/Vault'
```

I have also installed Phyton 3.12.0 and run the script with
``python3 ./dokuwiki-obsidian.py``. Unfortunately I always get the message ``Press any key to exit`` without anything happening.

I start the script under MacOS 10.14 from the terminal.

Which folder must be specified directly by Dokuwiki?
The webroot? The data folder in Dokuwiki or the pages folder with the actual pages?

**Comment by ReactiveMatter** [comment]
The source folder should be the data folder. It should contain pages and media folder for this script to run.

**Comment by Photographix** [comment]
Hello,

thanks for the feedback. 

Unfortunately, it still does not work after customization. Does the dokuwiki have to be prepared somehow? I use a normal dokuwiki without a markdown plugin, i.e. with standard dokuwiki syntax.

Is there a verbose mode for the script? Unfortunately, I am not a programmer and am not familiar with phython.

**Comment by ChenXuewen3** [comment]
在Dokuwiki中，有一些重要的文件夹需要由Dokuwiki直接指定或使用。其中，最重要的文件夹是“data”文件夹，它存储了Dokuwiki的各种数据，包括页面内容、插件、模板等。Dokuwiki需要能够直接访问这个文件夹以读取和写入数据。

另外，其他一些文件夹如“lib”文件夹和“local”文件夹也是Dokuwiki运行所必需的。

“lib”文件夹用于存放Dokuwiki的各种库文件和插件。

“local”文件夹用于存放本地用户的配置文件和个性化设置。

至于“page”文件夹，它通常位于“data”文件夹下，用于存储实际的页面内容。Dokuwiki会根据页面的ID将内容存储在不同的子文件夹中。

而“conf”文件夹则用于存放Dokuwiki的配置文件。

请注意，这些文件夹的位置和名称可能会因安装和配置的不同而有所变化。在进行任何修改之前，建议先备份你的Dokuwiki数据和配置文件，以防意外发生。

**Comment by ChenXuewen3** [comment]
In Dokuwiki, there are some important folders that need to be specified or used directly by Dokuwiki. The most important folder is the "data" folder, which stores various data for Dokuwiki, including page content, plugins, templates, and so on. Dokuwiki needs to be able to directly access this folder to read and write data.

In addition, other folders such as the "lib" folder and the "local" folder are also required for Dokuwiki to run.

The "lib" folder is used to store various library files and plugins for Dokuwiki.

The "local" folder is used to store the configuration files and personalized settings of local users.

As for the "page" folder, it is usually located under the "data" folder and is used to store the actual page content. Dokuwiki stores content in different subfolders based on the page's ID.

The "conf" folder is used to store Dokuwiki configuration files.

Please note that the location and name of these folders may vary depending on your installation and configuration. Before making any modifications, it is recommended to back up your Dokuwiki data and configuration files in case of unexpected errors.

**Comment by ReactiveMatter** [comment]
> Hello,
> 
> thanks for the feedback.
> 
> Unfortunately, it still does not work after customization. Does the dokuwiki have to be prepared somehow? I use a normal dokuwiki without a markdown plugin, i.e. with standard dokuwiki syntax.
> 
> Is there a verbose mode for the script? Unfortunately, I am not a programmer and am not familiar with phython.

This script converts notes from Dokuwiki markup only, and hence no modification is required.

To ensure that the script runs as expected, ensure the following things:
1. the `source_folder` variable should be the absolute path of your Dokuwiki data folder (having pages and media folder). E.g. `C:\\Dokuwiki\\data` (Note: For windows you will have to escape the backslash in the path)
2. the `destination_folder` variable should be the absolute path of the folder where you want to create the markdown files. Ensure that you have appropriate permissions to create files in this path.

In your case, try having a leading slash in your paths. If you are working on cloud, try downloading the data folder and converting them on local computer.
